version: '3.8'
services:
  web:
    build: .
    command: bash -c "pipenv run python manage.py migrate && pipenv run python manage.py runserver"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db